### ISSUE TITLE
Adding a new package does not seem to work

### ISSUE THREAD

**Issue by fniephaus** [j4yk/Squot#41]
Create a new class and add it to some new category. Then start a new project in the GitBrowser. Currently, you cannot add the category, because it does not appear in the package list. In my current image, I have replaced this list with the same list the Browser displays. However, when I add the newly created category, a new commit is empty. Have tried different things, can't get it working

**Comment by j4yk** [comment]
The commit issue is caused by #45. We'll have to discuss about the category selection, like here: https://github.com/j4yk/Squot/commit/53645c76645c10afea1cc79ad8118eb876d0fec5#commitcomment-21871742 Hence, #46 is a followup issue of this one.
