### ISSUE TITLE
Cannot push

### ISSUE THREAD

**Issue by fniephaus** [j4yk/Squot#43]
`(NeedGitCredentials for: url) signal` does not do anything in my image.
Where do I have to add my credentials?

**Comment by j4yk** [comment]
Currently, you have to use methods of SquitRepository (category "synchronizing"). I would like to organize it such that when there are no credentials, the user is prompted for some, and if these should be stored with the repository.

**Comment by fniephaus** [comment]
![image](https://cloud.githubusercontent.com/assets/2368856/25315903/56b1e788-285d-11e7-8619-e92a44735935.png)
😢
I'll take care of it...

**Comment by fniephaus** [comment]
A user can now manage credentials and it's ensured that credentials exists before pushing.
However now, I still can't push because of the same reason I can't fetch (#40).
