### ISSUE TITLE
Bogus diff when a package is absent in the previous snapshot

### ISSUE THREAD

**Issue by j4yk** [j4yk/Squot#45]
The commit dialog shows up empty and the diff content is empty as well.

![image](https://cloud.githubusercontent.com/assets/151175/25316221/f3030662-2862-11e7-9e28-b7388203e1a2.png)

The MCPatch is empty. It should include additions for all definitions in the package.

**Comment by j4yk** [comment]
This also makes it impossible to commit new packages properly.

**Comment by fniephaus** [comment]
I wasn't sure if this was just me, really annoying bug at the moment. I usually readd the project and `registerPackagesInStore` a couple of times and then eventually, I can commit again...

**Comment by j4yk** [comment]
4d0a95d (and ancestors) should fix this, please check and confirm

**Comment by fniephaus** [comment]
Yes, that fixed it. Thanks!
